sudo: required

language: ruby

services:
    - docker

before_script:
    - docker build -t thehunt33r/docker-brimir .
    - docker run -d -p 80:3000 thehunt33r/docker-brimir
    - docker ps -a
    - docker run thehunt33r/docker-brimir /bin/sh -c "psql -c 'CREATE DATABASE brimir_test;' -U postgres"
    - docker run thehunt33r/docker-brimir /bin/sh -c "cp config/database.travis.yml config/database.yml"
    - docker run thehunt33r/docker-brimir /bin/sh -c "bundle exec rake db:migrate"
